services:
  mysql:
    image: mysql:8.0
    container_name: cuple-database
    restart: no
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cuple
      MYSQL_ROOT_PASSWORD: root
      TZ: +00:00
    volumes:
      - ./.container/mysql/data:/var/lib/mysql
      - ./.container/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./.container/mysql/conf.d:/etc/mysql/conf.d
#    platform: linux/x86_64